using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
	using BepInEx;
	using BepInEx.Logging;
using HarmonyLib;
using UnityEngine;

namespace Stacking
{
	[BepInPlugin(GUID, pluginName, version)]
#if BELOWZERO
	[BepInProcess("SubnauticaZero.exe")]
#else
	[BepInProcess("Subnautica.exe")]
#endif
	public class StackablesPlugin : BaseUnityPlugin
	{
		#region Declarations
		internal const string
			pluginName = "StackableInventory",
			version = "0.1.0.0",
			AUTHOR = "dawrecka",
			GUID = "com." + AUTHOR + "." + pluginName;
		#endregion

		private static readonly Harmony harmony = new Harmony(GUID);

		public static int defaultStackLimit { get; } = 10; // Stack limit for any TechType not explicitly listed in the dictionary below
		// Note that this only applies to items which have a Pickupable, aren't equipment - that is, have EquipmentType.None - and don't have a Living component.

		// Dictionary of predefined stack limits. Any stackable not in this collection will use the default value.
		private static readonly Dictionary<TechType, int> StackLimits = new Dictionary<TechType, int>()
		{
			{ TechType.ReactorRod, 4 },
			{ TechType.SafeShallowsEgg, 4 },
			{ TechType.KelpForestEgg, 4 },
			{ TechType.GrassyPlateausEgg, 4 },
			{ TechType.GrandReefsEgg, 4 },
			{ TechType.MushroomForestEgg, 4 },
			{ TechType.KooshZoneEgg, 4 },
			{ TechType.TwistyBridgesEgg, 4 },
			{ TechType.LavaZoneEgg, 4 },
			{ TechType.StalkerEgg, 4 },
			{ TechType.ReefbackEgg, 4 },
			{ TechType.SpadefishEgg, 4 },
			{ TechType.RabbitrayEgg, 4 },
			{ TechType.MesmerEgg, 4 },
			{ TechType.JumperEgg, 4 },
			{ TechType.SandsharkEgg, 4 },
			{ TechType.JellyrayEgg, 4 },
			{ TechType.BonesharkEgg, 4 },
			{ TechType.CrabsnakeEgg, 4 },
			{ TechType.ShockerEgg, 4 },
			{ TechType.GasopodEgg, 4 },
			{ TechType.RabbitrayEggUndiscovered, 4 },
			{ TechType.JellyrayEggUndiscovered, 4 },
			{ TechType.StalkerEggUndiscovered, 4 },
			{ TechType.ReefbackEggUndiscovered, 4 },
			{ TechType.JumperEggUndiscovered, 4 },
			{ TechType.BonesharkEggUndiscovered, 4 },
			{ TechType.GasopodEggUndiscovered, 4 },
			{ TechType.MesmerEggUndiscovered, 4 },
			{ TechType.SandsharkEggUndiscovered, 4 },
			{ TechType.ShockerEggUndiscovered, 4 },
			{ TechType.GenericEgg, 4 },
			{ TechType.CrashEgg, 4 },
			{ TechType.CrashEggUndiscovered, 4 },
			{ TechType.CrabsquidEgg, 4 },
			{ TechType.CrabsquidEggUndiscovered, 4 },
			{ TechType.CutefishEgg, 4 },
			{ TechType.CutefishEggUndiscovered, 4 },
			{ TechType.LavaLizardEgg, 4 },
			{ TechType.LavaLizardEggUndiscovered, 4 },
			{ TechType.CrabsnakeEggUndiscovered, 4 },
			{ TechType.SpadefishEggUndiscovered, 4 },
			{ TechType.CookedPeeper, 4 },
			{ TechType.CookedHoleFish, 4 },
			{ TechType.CookedGarryFish, 4 },
			{ TechType.CookedReginald, 4 },
			{ TechType.CookedBladderfish, 4 },
			{ TechType.CookedHoverfish, 4 },
			{ TechType.CookedSpadefish, 4 },
			{ TechType.CookedBoomerang, 4 },
			{ TechType.CookedEyeye, 4 },
			{ TechType.CookedOculus, 4 },
			{ TechType.CookedHoopfish, 4 },
			{ TechType.CookedSpinefish, 4 },
			{ TechType.CookedLavaEyeye, 4 },
			{ TechType.CookedLavaBoomerang, 4 },
			{ TechType.CuredPeeper, 4 },
			{ TechType.CuredHoleFish, 4 },
			{ TechType.CuredGarryFish, 4 },
			{ TechType.CuredReginald, 4 },
			{ TechType.CuredBladderfish, 4 },
			{ TechType.CuredHoverfish, 4 },
			{ TechType.CuredSpadefish, 4 },
			{ TechType.CuredBoomerang, 4 },
			{ TechType.CuredEyeye, 4 },
			{ TechType.CuredOculus, 4 },
			{ TechType.CuredHoopfish, 4 },
			{ TechType.CuredSpinefish, 4 },
			{ TechType.CuredLavaEyeye, 4 },
			{ TechType.CuredLavaBoomerang, 4 },
		};

		// We don't want to stack equipables or living creatures
		// While we could simply add them to the limits dictionary with a value of 1, adding them instead to a blacklist,
		// and implementing that blacklist as a HashSet, gives us a fast, inexpensive "no" on a huge number of vanilla TechTypes.
		// Modded TechTypes, we'll just have to use the more-expensive checks.
		internal static readonly HashSet<TechType> blacklist = new()
		{
			TechType.None,
			TechType.LimestoneChunk,
			TechType.CalciteOld,
			TechType.DolomiteOld,
			TechType.CalciumChunk,
			TechType.Placeholder,
			TechType.CarbonOld,
			TechType.EthanolOld,
			TechType.EthyleneOld,
			TechType.HydrogenOld,
			TechType.SandLoot,
			TechType.BatteryAcidOld,
			TechType.SandstoneChunk,
			TechType.BasaltChunk,
			TechType.ShaleChunk,
			TechType.ObsidianChunk,
			TechType.Fiber,
			TechType.Enamel,
			TechType.AcidOld,
			TechType.VesselOld,
			TechType.CombustibleOld,
			TechType.OpalGem,
			TechType.Uranium,
			TechType.AminoAcids,
			TechType.Graphene,
			TechType.Nanowires,
			TechType.PrecursorIonCrystalMatrix,
			TechType.DiveSuit,
			TechType.ShipComputerOld,
			TechType.Fins,
			TechType.Tank,
			TechType.Battery,
			TechType.Knife,
			TechType.Drill,
			TechType.Flashlight,
			TechType.Beacon,
			TechType.Builder,
			TechType.PDA,
			TechType.EscapePod,
			TechType.Compass,
			TechType.AirBladder,
			TechType.Terraformer,
			TechType.Pipe,
			TechType.Thermometer,
			TechType.DiveReel,
			TechType.Rebreather,
			TechType.RadiationSuit,
			TechType.RadiationHelmet,
			TechType.RadiationGloves,
			TechType.ReinforcedDiveSuit,
			TechType.Scanner,
			TechType.FireExtinguisher,
			TechType.MapRoomHUDChip,
			TechType.PipeSurfaceFloater,
			TechType.CyclopsDecoy,
			TechType.DoubleTank,
			TechType.ReinforcedGloves,
			TechType.Welder,
			TechType.Seaglide,
			TechType.Constructor,
			TechType.Transfuser,
			TechType.Flare,
			TechType.StasisRifle,
			TechType.BuildBot,
			TechType.PropulsionCannon,
			TechType.Gravsphere,
			TechType.SmallStorage,
			TechType.StasisSphere,
			TechType.LaserCutter,
			TechType.LEDLight,
			TechType.DiamondBlade,
			TechType.HeatBlade,
			TechType.LithiumIonBattery,
			TechType.PlasteelTank,
			TechType.HighCapacityTank,
			TechType.UltraGlideFins,
			TechType.SwimChargeFins,
			TechType.RepulsionCannon,
			TechType.WaterFiltrationSuit,
			TechType.PowerGlide,
			TechType.CompostCreepvine,
			TechType.ProcessUranium,
			TechType.PrecursorIonEnergyBlueprint,
			TechType.FabricatorBlueprintOld,
			TechType.ConstructorBlueprint,
			TechType.CyclopsBlueprint,
			TechType.FragmentAnalyzerBlueprintOld,
			TechType.LockerBlueprint,
			TechType.SpecialHullPlateBlueprintOld,
			TechType.BikemanHullPlateBlueprintOld,
			TechType.EatMyDictionHullPlateBlueprintOld,
			TechType.DevTestItemBlueprintOld,
			TechType.SeamothBlueprint,
			TechType.StasisRifleBlueprint,
			TechType.ExosuitBlueprint,
			TechType.TransfuserBlueprint,
			TechType.TerraformerBlueprint,
			TechType.ReinforceHullBlueprint,
			TechType.WorkbenchBlueprint,
			TechType.PropulsionCannonBlueprint,
			TechType.SpecimenAnalyzerBlueprint,
			TechType.BioreactorBlueprint,
			TechType.ThermalPlantBlueprint,
			TechType.NuclearReactorBlueprint,
			TechType.MoonpoolBlueprint,
			TechType.FiltrationMachineBlueprint,
			TechType.TechlightBlueprint,
			TechType.LEDLightBlueprint,
			TechType.CyclopsHullBlueprint,
			TechType.CyclopsBridgeBlueprint,
			TechType.CyclopsEngineBlueprint,
			TechType.CyclopsDockingBayBlueprint,
			TechType.SpotlightBlueprint,
			TechType.RadioBlueprint,
			TechType.StarshipCargoCrateBlueprint,
			TechType.StarshipCircuitBoxBlueprint,
			TechType.StarshipDeskBlueprint,
			TechType.StarshipChairBlueprint,
			TechType.StarshipMonitorBlueprint,
			TechType.SolarPanelBlueprint,
			TechType.PowerTransmitterBlueprint,
			TechType.BaseUpgradeConsoleBlueprint,
			TechType.BaseObservatoryBlueprint,
			TechType.BaseWaterParkBlueprint,
			TechType.PictureFrameBlueprint,
			TechType.BaseRoomBlueprint,
			TechType.BaseBulkheadBlueprint,
			TechType.SeaglideBlueprint,
			TechType.BatteryChargerBlueprint,
			TechType.PowerCellChargerBlueprint,
			TechType.FarmingTrayBlueprint,
			TechType.SignBlueprint,
			TechType.BenchBlueprint,
			TechType.PlanterPotBlueprint,
			TechType.PlanterBoxBlueprint,
			TechType.PlanterShelfBlueprint,
			TechType.AquariumBlueprint,
			TechType.ReinforcedDiveSuitBlueprint,
			TechType.RadiationSuitBlueprint,
			TechType.WaterFiltrationSuitBlueprint,
			TechType.ScannerRoomBlueprint,
			TechType.BasePlanterBlueprint,
			TechType.PlanterPot2Blueprint,
			TechType.PlanterPot3Blueprint,
			TechType.MedicalCabinetBlueprint,
			TechType.BaseMapRoomBlueprint,
			TechType.SeamothFragment,
			TechType.StasisRifleFragment,
			TechType.ExosuitFragment,
			TechType.TransfuserFragment,
			TechType.TerraformerFragment,
			TechType.ReinforceHullFragment,
			TechType.WorkbenchFragment,
			TechType.PropulsionCannonFragment,
			TechType.BioreactorFragment,
			TechType.ThermalPlantFragment,
			TechType.NuclearReactorFragment,
			TechType.MoonpoolFragment,
			TechType.BaseFiltrationMachineFragment,
			TechType.CyclopsHullFragment,
			TechType.CyclopsBridgeFragment,
			TechType.CyclopsEngineFragment,
			TechType.CyclopsDockingBayFragment,
			TechType.SeaglideFragment,
			TechType.ConstructorFragment,
			TechType.SolarPanelFragment,
			TechType.PowerTransmitterFragment,
			TechType.BaseUpgradeConsoleFragment,
			TechType.BaseObservatoryFragment,
			TechType.BaseWaterParkFragment,
			TechType.RadioFragment,
			TechType.BaseRoomFragment,
			TechType.BaseBulkheadFragment,
			TechType.BatteryChargerFragment,
			TechType.PowerCellChargerFragment,
			TechType.ScannerRoomFragment,
			TechType.SpecimenAnalyzerFragment,
			TechType.FarmingTrayFragment,
			TechType.SignFragment,
			TechType.PictureFrameFragment,
			TechType.BenchFragment,
			TechType.PlanterPotFragment,
			TechType.PlanterBoxFragment,
			TechType.PlanterShelfFragment,
			TechType.AquariumFragment,
			TechType.ReinforcedDiveSuitFragment,
			TechType.RadiationSuitFragment,
			TechType.WaterFiltrationSuitFragment,
			TechType.BuilderFragment,
			TechType.LEDLightFragment,
			TechType.TechlightFragment,
			TechType.SpotlightFragment,
			TechType.BaseMapRoomFragment,
			TechType.BaseBioReactorFragment,
			TechType.BaseNuclearReactorFragment,
			TechType.LaserCutterFragment,
			TechType.BeaconFragment,
			TechType.GravSphereFragment,
			TechType.BaseLargeRoomFragment,
			TechType.BaseLargeGlassDomeFragment,
			TechType.BaseGlassDomeFragment,
			TechType.ReefbackShell,
			TechType.ReefbackTissue,
			TechType.ReefbackAdvancedStructure,
			TechType.ReefbackDNA,
			TechType.Workbench,
			TechType.HullReinforcementModule,
			TechType.Fabricator,
			TechType.Aquarium,
			TechType.Locker,
			TechType.Spotlight,
			TechType.DiveHatch,
			TechType.CurrentGenerator,
			TechType.FragmentAnalyzer,
			TechType.SpecialHullPlate,
			TechType.BikemanHullPlate,
			TechType.EatMyDictionHullPlate,
			TechType.DevTestItem,
			TechType.SpecimenAnalyzer,
			TechType.HullReinforcementModule2,
			TechType.HullReinforcementModule3,
			TechType.PowerUpgradeModule,
			TechType.SolarPanel,
			TechType.Sign,
			TechType.PowerTransmitter,
			TechType.Accumulator,
			TechType.Bioreactor,
			TechType.ThermalPlant,
			TechType.NuclearReactor,
			TechType.SmallLocker,
			TechType.Bench,
			TechType.PictureFrame,
			TechType.PlanterPot,
			TechType.PlanterBox,
			TechType.PlanterShelf,
			TechType.FarmingTray,
			TechType.FiltrationMachine,
			TechType.Techlight,
			TechType.Radio,
			TechType.PlanterPot2,
			TechType.PlanterPot3,
			TechType.MedicalCabinet,
			TechType.CyclopsHullModule1,
			TechType.CyclopsHullModule2,
			TechType.SingleWallShelf,
			TechType.WallShelves,
			TechType.Bed1,
			TechType.Bed2,
			TechType.NarrowBed,
			TechType.BatteryCharger,
			TechType.PowerCellCharger,
			TechType.Incubator,
			TechType.HatchingEnzymes,
			TechType.EnyzmeCloud,
			TechType.EnzymeCureBall,
			TechType.Centrifuge,
			TechType.CyclopsShieldModule,
			TechType.CyclopsSonarModule,
			TechType.CyclopsSeamothRepairModule,
			TechType.CyclopsDecoyModule,
			TechType.CyclopsFireSuppressionModule,
			TechType.CyclopsFabricator,
			TechType.CyclopsThermalReactorModule,
			TechType.CyclopsHullModule3,
			TechType.StarshipCargoCrate,
			TechType.StarshipCircuitBox,
			TechType.StarshipDesk,
			TechType.StarshipChair,
			TechType.StarshipMonitor,
			TechType.StarshipChair2,
			TechType.StarshipChair3,
			TechType.LuggageBag,
			TechType.ArcadeGorgetoy,
			TechType.LabEquipment1,
			TechType.LabEquipment2,
			TechType.LabEquipment3,
			TechType.CoffeeVendingMachine,
			TechType.BarTable,
			TechType.Cap1,
			TechType.Cap2,
			TechType.LabContainer,
			TechType.LabContainer2,
			TechType.LabContainer3,
			TechType.Trashcans,
			TechType.LabTrashcan,
			TechType.VendingMachine,
			TechType.LabCounter,
			TechType.StarshipSouvenir,
			TechType.PosterAurora,
			TechType.PosterExoSuit1,
			TechType.PosterExoSuit2,
			TechType.PosterKitty,
			TechType.ToyCar,
			TechType.Seamoth,
			TechType.Exosuit,
			TechType.CrashedShip,
			TechType.Cyclops,
			TechType.Audiolog,
			TechType.Signal,
			TechType.SeamothReinforcementModule,
			TechType.VehiclePowerUpgradeModule,
			TechType.SeamothSolarCharge,
			TechType.VehicleStorageModule,
			TechType.SeamothElectricalDefense,
			TechType.VehicleArmorPlating,
			TechType.LootSensorMetal,
			TechType.LootSensorLithium,
			TechType.LootSensorFragment,
			TechType.SeamothTorpedoModule,
			TechType.SeamothSonarModule,
			// TechType.WhirlpoolTorpedo,
			TechType.VehicleHullModule1,
			TechType.VehicleHullModule2,
			TechType.VehicleHullModule3,
			TechType.ExosuitJetUpgradeModule,
			TechType.ExosuitDrillArmModule,
			TechType.ExosuitThermalReactorModule,
			TechType.ExosuitClawArmModule,
			// TechType.GasTorpedo,
			TechType.ExosuitPropulsionArmModule,
			TechType.ExosuitGrapplingArmModule,
			TechType.ExosuitTorpedoArmModule,
			TechType.ExosuitDrillArmFragment,
			TechType.ExosuitPropulsionArmFragment,
			TechType.ExosuitGrapplingArmFragment,
			TechType.ExosuitTorpedoArmFragment,
			TechType.ExosuitClawArmFragment,
			TechType.ExoHullModule1,
			TechType.ExoHullModule2,
			TechType.MapRoomUpgradeScanRange,
			TechType.MapRoomUpgradeScanSpeed,
			TechType.Creepvine,
			TechType.HoleFish,
			TechType.Jumper,
			TechType.CreepvineSeedCluster,
			TechType.Peeper,
			TechType.Oculus,
			TechType.RabbitRay,
			TechType.GarryFish,
			TechType.Slime,
			TechType.Crash,
			TechType.Boomerang,
			TechType.LavaLarva,
			TechType.Stalker,
			TechType.Eyeye,
			TechType.Bloom,
			TechType.Bladderfish,
			TechType.Hoverfish,
			TechType.Jellyray,
			TechType.Reefback,
			TechType.Reginald,
			TechType.Spadefish,
			TechType.Grabcrab,
			TechType.Floater,
			TechType.Gasopod,
			TechType.Sandshark,
			TechType.Player,
			TechType.Bleeder,
			TechType.Rockgrub,
			TechType.CrashHome,
			TechType.CreepvinePiece,
			TechType.GasPod,
			TechType.Hoopfish,
			TechType.HoopfishSchool,
			TechType.RockPuncher,
			TechType.BoneShark,
			TechType.Mesmer,
			TechType.SeaTreader,
			TechType.SeaEmperor,
			TechType.Cutefish,
			TechType.Crabsnake,
			TechType.ReaperLeviathan,
			TechType.CaveCrawler,
			TechType.Skyray,
			TechType.Biter,
			TechType.SkyrayNonRoosting,
			TechType.Shocker,
			TechType.Spinefish,
			TechType.Shuttlebug,
			TechType.Blighter,
			TechType.Warper,
			TechType.CrabSquid,
			TechType.LavaLizard,
			TechType.SpineEel,
			TechType.SeaDragon,
			TechType.LavaBoomerang,
			TechType.LavaEyeye,
			TechType.SeaEmperorBaby,
			TechType.WarperSpawner,
			TechType.GhostRayBlue,
			TechType.GhostRayRed,
			TechType.ReefbackBaby,
			TechType.PrecursorDroid,
			TechType.GhostLeviathan,
			TechType.SeaEmperorLeviathan,
			TechType.SeaEmperorJuvenile,
			TechType.GhostLeviathanJuvenile,
			TechType.HoleFishAnalysis,
			TechType.PeeperAnalysis,
			TechType.BladderfishAnalysis,
			TechType.GarryFishAnalysis,
			TechType.HoverfishAnalysis,
			TechType.ReginaldAnalysis,
			TechType.SpadefishAnalysis,
			TechType.BoomerangAnalysis,
			TechType.EyeyeAnalysis,
			TechType.OculusAnalysis,
			TechType.HoopfishAnalysis,
			TechType.AnalysisTreeOld,
			TechType.SpinefishAnalysis,
			TechType.PlantPlaceholder,
			TechType.BallClusters,
			TechType.BarnacleSuckers,
			TechType.BlueBarnacle,
			TechType.BlueBarnacleCluster,
			TechType.BlueCoralTubes,
			TechType.RedGrass,
			TechType.GreenGrass,
			TechType.Mohawk,
			TechType.GreenReeds,
			TechType.BlueJeweledDisk,
			TechType.GreenJeweledDisk,
			TechType.PurpleJeweledDisk,
			TechType.RedJeweledDisk,
			TechType.SmallKoosh,
			TechType.MediumKoosh,
			TechType.LargeKoosh,
			TechType.HugeKoosh,
			TechType.MembrainTree,
			TechType.PurpleFan,
			TechType.PurpleTentacle,
			TechType.RedSeaweed,
			TechType.CoralOldPlaceholder,
			TechType.CoralShellPlate,
			TechType.SmallFan,
			TechType.SmallFanCluster,
			TechType.BigCoralTubes,
			TechType.TreeMushroom,
			TechType.BlueCluster,
			TechType.BrownTubes,
			TechType.BloodGrass,
			TechType.HeatArea,
			TechType.BloodRoot,
			TechType.BloodVine,
			TechType.PinkFlower,
			TechType.BulboTree,
			TechType.PurpleVegetablePlant,
			TechType.MelonPlant,
			TechType.BluePalm,
			TechType.GabeSFeather,
			TechType.SeaCrown,
			TechType.OrangePetalsPlant,
			TechType.EyesPlant,
			TechType.RedGreenTentacle,
			TechType.PurpleStalk,
			TechType.RedBasketPlant,
			TechType.RedBush,
			TechType.RedConePlant,
			TechType.ShellGrass,
			TechType.SpottedLeavesPlant,
			TechType.RedRollPlant,
			TechType.PurpleBranches,
			TechType.SnakeMushroom,
			TechType.GenericJeweledDisk,
			TechType.FloatingStone,
			TechType.BlueAmoeba,
			TechType.RedTipRockThings,
			TechType.BlueTipLostRiverPlant,
			TechType.BlueLostRiverLilly,
			TechType.LargeFloater,
			TechType.PiecePlaceholder,
			TechType.EnvironmentPlaceholder,
			TechType.Boulder,
			TechType.PurpleBrainCoral,
			TechType.HangingStinger,
			TechType.SpikePlant,
			TechType.BrainCoral,
			TechType.CoveTree,
			TechType.MonsterSkeleton,
			TechType.SeaDragonSkeleton,
			TechType.ReaperSkeleton,
			TechType.CaveSkeleton,
			TechType.HugeSkeleton,
			TechType.PrecursorKey_PurpleFragment,
			TechType.PrecursorKeyTerminal,
			TechType.PrecursorTeleporter,
			TechType.PrecursorEnergyCore,
			TechType.PrecursorThermalPlant,
			TechType.PrecursorWarper,
			TechType.PrecursorFishSkeleton,
			TechType.PrecursorScanner,
			TechType.PrecursorLabCacheContainer1,
			TechType.PrecursorLabCacheContainer2,
			TechType.PrecursorLabTable,
			TechType.PrecursorSeaDragonSkeleton,
			TechType.PrecursorSensor,
			TechType.PrecursorPrisonArtifact1,
			TechType.PrecursorPrisonArtifact2,
			TechType.PrecursorPrisonArtifact3,
			TechType.PrecursorPrisonArtifact4,
			TechType.PrecursorPrisonArtifact5,
			TechType.PrecursorPrisonArtifact6,
			TechType.PrecursorPrisonArtifact7,
			TechType.PrecursorPrisonArtifact8,
			TechType.PrecursorPrisonArtifact9,
			TechType.PrecursorPrisonArtifact10,
			TechType.PrecursorPrisonArtifact11,
			TechType.PrecursorPrisonArtifact12,
			TechType.PrecursorPipeRoomIncomingPipe,
			TechType.PrecursorPipeRoomOutgoingPipe,
			TechType.PrecursorPrisonLabEmperorFetus,
			TechType.PrecursorPrisonLabEmperorEgg,
			TechType.PrecursorPrisonAquariumPipe,
			TechType.PrecursorPrisonAquariumFinalTeleporter,
			TechType.PrecursorPrisonAquariumIncubatorEggs,
			TechType.PrecursorPrisonAquariumIncubator,
			TechType.PrecursorSurfacePipe,
			TechType.PrecursorPrisonArtifact13,
			TechType.PrecursorPrisonIonGenerator,
			TechType.PrecursorPrisonOutposts,
			TechType.ObservatoryOld,
			TechType.PrecursorLostRiverBrokenAnchor,
			TechType.PrecursorLostRiverLabRays,
			TechType.PrecursorLostRiverLabBones,
			TechType.PrecursorLostRiverLabEgg,
			TechType.PrecursorLostRiverProductionLine,
			TechType.PrecursorLostRiverWarperParts,
			TechType.Snack1,
			TechType.Snack2,
			TechType.Snack3,
			TechType.MembraneOld,
			TechType.Unobtanium,
			TechType.BaseRoom,
			TechType.BaseHatch,
			TechType.BaseWall,
			TechType.BaseDoor,
			TechType.BaseLadder,
			TechType.BaseWindow,
			TechType.PowerGeneratorOld,
			TechType.UnusedOld,
			TechType.BaseCorridor,
			TechType.BaseFoundation,
			TechType.BaseCorridorI,
			TechType.BaseCorridorL,
			TechType.BaseCorridorT,
			TechType.BaseCorridorX,
			TechType.BaseReinforcement,
			TechType.BaseBulkhead,
			TechType.BaseCorridorGlassI,
			TechType.BaseCorridorGlassL,
			TechType.BaseObservatory,
			TechType.BaseConnector,
			TechType.BaseMoonpool,
			TechType.BaseCorridorGlass,
			TechType.BaseUpgradeConsole,
			TechType.BasePlanter,
			TechType.BaseFiltrationMachine,
			TechType.BaseWaterPark,
			TechType.BaseMapRoom,
			TechType.MapRoomCamera,
			TechType.BaseBioReactor,
			TechType.BaseNuclearReactor,
			TechType.BasePipeConnector,
			TechType.BaseRechargePlatform,
			TechType.BaseControlRoom,
			TechType.BaseWallFoundation,
			TechType.BaseLargeRoom,
			TechType.OldBasePartitionI,
			TechType.OldBasePartitionL,
			TechType.OldBasePartitionT,
			TechType.OldBasePartitionX,
			TechType.BasePartitionDoor,
			TechType.BaseGlassDome,
			TechType.BasePartition,
			TechType.BaseLargeGlassDome,
			TechType.RocketBase,
			TechType.RocketBaseLadder,
			TechType.RocketStage1,
			TechType.RocketStage2,
			TechType.RocketStage3,
			TechType.TimeCapsule,
			TechType.DioramaHullPlate,
			TechType.MarkiplierHullPlate,
			TechType.MuyskermHullPlate,
			TechType.LordMinionHullPlate,
			TechType.JackSepticEyeHullPlate,
			TechType.Poster,
			TechType.IGPHullPlate,
			TechType.GilathissHullPlate,
			TechType.Marki1,
			TechType.Marki2,
			TechType.JackSepticEye,
			TechType.EatMyDiction,
			TechType.RadiationLeakPoint,
			TechType.SomethingPlaceholder,
			TechType.Fragment,
			TechType.Wreck,
			TechType.CountOld,
			TechType.Databox
		};

		private static HashSet<TechType> quickRefBlacklist = new HashSet<TechType>();

		// This function should only be called for objects with a Pickupable component, so we don't need to explicitly exclude things like drillables or large creatures.
		public static int GetStackLimitForGameObject(GameObject go)
		{
			if (go == null) return 0;

			TechType tt = CraftData.GetTechType(go);
			if (tt == TechType.None)
				return 0;

			if(blacklist.Contains(tt) || quickRefBlacklist.Contains(tt))
				return 1;

			// First, if the object is Equipment, then it shouldn't be stackable
			// Eggs and anything alive is also non-stackable.
			if (TechData.GetEquipmentType(tt) == EquipmentType.None && go.GetComponent<CreatureEgg>() == null && go.GetComponent<Living>() == null)
			{
				return GetStackLimit(CraftData.GetTechType(go));
			}

			if (!quickRefBlacklist.Contains(tt))
				quickRefBlacklist.Add(tt);
			return 1;
		}

		public static int GetStackLimit(TechType tt)
		{
			if (blacklist.Contains(tt))
			{
				return 1;
			}

			int limit = StackLimits.GetOrDefault(tt, defaultStackLimit);
			if (limit < 2)
			{
				blacklist.Add(tt);
				return 1;
			}

			return limit;
		}

		public void Awake()
		{
			var assembly = Assembly.GetExecutingAssembly();
			harmony.PatchAll(assembly);
		}
	}
}
